### ISSUE TITLE
PIP install fails on README.md

### ISSUE THREAD

**Issue by regner** [Regner/eveimageserver#1]
DEPRECATION: --no-install, --no-download, --build, and --no-clean are deprecated.  See https://github.com/pypa/pip/issues/906.
Downloading/unpacking eveimageserver==0.1.0
  Downloading eveimageserver-0.1.0.tar.gz
  Running setup.py (path:C:\Users\regner\AppData\Local\Temp\pycharm-packaging0.tmp\eveimageserver\setup.py) egg_info for package eveimageserver
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\regner\AppData\Local\Temp\pycharm-packaging0.tmp\eveimageserver\setup.py", line 21, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\regner\AppData\Local\Temp\pycharm-packaging0.tmp\eveimageserver\setup.py", line 21, in <module>

```
long_description=open('README.md').read(),
```

IOError: [Errno 2] No such file or directory: 'README.md'

**Comment by regner** [comment]
Needs a manifest.in
